# Generated by Django 4.1.1 on 2022-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='piority',
            field=models.BooleanField(default=False),
        ),
    ]
