# Generated by Django 4.1.1 on 2022-11-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_piority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='text',
            new_name='todo_text',
        ),
    ]
