# Generated by Django 4.1.1 on 2022-11-29 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todoitem_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
