# Generated by Django 4.1.1 on 2022-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todoitem_creation_time_todoitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='piority',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
