# Generated by Django 4.1.1 on 2022-11-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todoitem_priority_todoitem_piority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='piority',
        ),
    ]
